### ISSUE TITLE
server not running

### ISSUE THREAD

**Issue by turbo420** [pspiworld/piworld#1]
it makes the world file but will not run the ./server.py error is 
Traceback (most recent call last):
  File "./server.py", line 3, in <module>
    from world import World
  File "/home/pi/Desktop/piworld/world.py", line 7, in <module>
    dll = CDLL('./world')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./world: undefined symbol: config

what is  miss something?? 
thanks for help

**Comment by pspiworld** [comment]
Fixed in commit c81b5dd - you'll have to rebuild the world file adding -DSERVER to the gcc command:

    gcc -DSERVER -std=c99 -O3 -fPIC -shared -o world -I src -I deps/noise deps/noise/noise.c src/world.c

**Comment by turbo420** [comment]
working now but blocks in server world are showing up in local world 
Thanks for the help

**Comment by pspiworld** [comment]
> working now but blocks in server world are showing up in local world

A possible workaround is to remove any journal files left over:

* Stop all piworld clients and server.
* Backup all piworld directories, including ~/.piworld if you are using the binary release.
* In each piworld directory remove any file that ends with -journal.
* Restart server.py and clients.

This may delete the last few edits made, so make sure to backup all files first.
